---

- import_tasks: configure-hostkeys.yml
  tags: ['ssh-server', 'ssh-server-configure-hostkeys']

- import_tasks: configure-moduli.yml
  tags: ['ssh-server', 'ssh-server-configure-moduli']

- name: Setup /etc/ssh/sshd_config
  template:
    src:   sshd_config.j2
    dest:  '{{ ssh_server_config_dir }}/sshd_config'
    owner: root
    group: root
    mode:  0640
    validate: 'sshd -t -f %s'
  notify: [ 'test-and-restart-sshd' ]
