---

- name: Get OpenSSH server version
  # noqa 306
  environment:
    LC_MESSAGES: 'C'
  shell: >-
    /usr/bin/env sshd -v 2>&1
    | grep --perl-regexp --only-matching --regexp="(?<=OpenSSH_)[0-9\.]+"
  when: ansible_local.ssh_server.version_full is not defined
  register: _ssh_server__version_raw
  changed_when: false
  check_mode: false

- name: Create _ssh_server__version variable
  set_fact:
    _ssh_server__version: '{{
        _ssh_server__version_raw.stdout
        if _ssh_server__version_raw is not skipped
        else ansible_local.ssh_server.version_full
      }}'

- name: Importing host keys tasks
  import_tasks: configure-hostkeys.yml
  tags: ['ssh-server', 'ssh-server-configure', 'ssh-server-configure-hostkeys']

- name: Importing moduli tasks
  import_tasks: configure-moduli.yml
  tags: ['ssh-server', 'ssh-server-configure', 'ssh-server-configure-moduli']

- name: Setup /etc/ssh/sshd_config
  template:
    src: sshd_config.j2
    dest: '{{ ssh_server__config_file }}'
    owner: root
    group: root
    mode: 0640
    validate: '/usr/bin/env sshd -t -f %s'
  notify: ['test-and-restart-sshd']

- name: Configure service environment variables
  template:
    src: sshd.environment.j2
    dest: '{{ ssh_server__service_environment }}'
    owner: root
    group: root
    mode: 0640
  when: ssh_server__service_environment is defined
  notify: ['test-and-restart-sshd']
