---

- name: Check if banner file exists
  stat:
    path: '{{ ssh_server__banner }}'
  when: ssh_server__banner != 'none'
  register: _ssh_server__banner_file

- name: Assert banner file exists
  fail:
    msg: 'The banner file must exists'
  when: ssh_server__banner != 'none' and not _ssh_server__banner_file.stat.exists
