---
# tasks file for ssh-server

- name: Include the OS specific variables
  include_vars: '{{ item }}'
  with_first_found:
    - files:
        - '{{ ansible_distribution }}-{{ ansible_distribution_version }}.yml'
        - '{{ ansible_distribution }}.yml'
        - '{{ ansible_os_family }}.yml'
        - defaults.yml
      skip: true
  tags: ['always']

- import_tasks: init.yml
  tags: ['always']

- import_tasks: install.yml
  tags: ['ssh-server', 'ssh-server-install']

- import_tasks: configure.yml
  tags: ['ssh-server', 'ssh-server-configure']

- import_tasks: service.yml
  tags: ['ssh-server', 'ssh-server-service']

- include_tasks: facts.yml
  when: ssh_server__facts|bool
  tags: ['ssh-server', 'ssh-server-facts']
