---

- name: Ensure systemd override directory state
  file:
    path: '{{ ssh_server__systemd_override_options_dir }}'
    state: directory
  when: ansible_service_mgr == 'systemd'
  register: _ssh_server__service_dir
  notify: ['restart-ssh-server']

- name: Install systemd options override file
  template:
    src: override.systemd.j2
    dest: '{{ ssh_server__systemd_override_options_dir }}/override.conf'
  when: ansible_service_mgr == 'systemd'
  register: _ssh_server__service_override
  notify: ['restart-ssh-server']

- name: Reload systemd
  systemd:
    daemon_reload: true
  when: ansible_service_mgr == 'systemd'
    and (
      _ssh_server__service_dir is changed
      or _ssh_server__service_override is changed
    )

- name: Ensure ssh server is started and enabled on boot
  service:
    name: '{{ ssh_server__service_name }}'
    enabled: '{{ ssh_server__service_enabled|bool }}'
    state: "{{ ssh_server__service_enabled|bool|ternary('started', 'stopped') }}"
