---
# handlers file for ssh-server

- name: test-and-restart-sshd
  command: sshd -t
  notify: [ 'restart-sshd' ]

- name: restart-sshd
  service:
    name: '{{ ssh_server__service_name }}'
    state: restarted
