---
- name: Start openssh daemon
  service: 
    name: '{{ sshd__service_name }}'
    state: started

- name: Test ssh daemon configuration and restart
  command: sshd -t
  notify: [ 'Restart sshd' ]

- name: Restart sshd
  service:
    name: '{{ sshd__service_name }}'
    state: restarted
