---
# handlers file for ssh-server

- name: test-and-restart-sshd
  shell: >-
    /usr/bin/env mkdir -p /run/sshd
    && /usr/bin/env sshd -t -f {{ ssh_server__config_file }}
  check_mode: false
  notify: ['restart-ssh-server']

- name: restart-ssh-server
  service:
    name: '{{ ssh_server__service_name }}'
    state: restarted
