---
- name: Converge
  hosts: all
  any_errors_fatal: true
  tasks:
    - name: "Include turgon37.ssh_server"
      include_role:
        name: ansible-ssh-server
  vars:
    ssh_server__match_list_global:
      - match: LocalAddress 127.0.0.1
        options:
          - AllowUsers test
          - 6.0: AuthorizedKeysCommand /bin/true
            1.0:
              - AuthenticationMethods publickey
              - AllowUsers root
      - '{{ ssh_server__match_group_sftponly }}'
