---
- name: Converge
  hosts: all
  any_errors_fatal: true
  tasks:
    - name: "Include turgon37.ssh_server"
      include_role:
        name: ansible-ssh-server
  vars:
    ssh_server__service_enabled: false
    ssh_server__match_list_global:
      - match: LocalAddress 127.0.0.1
        options:
          - AllowUsers test
          - 8.2: AuthorizedKeysCommand /bin/true
            6.0:
              - AuthenticationMethods publickey
              - AllowUsers root
      - '{{ ssh_server__match_group_sftponly }}'
